### ISSUE TITLE
Incorrect output

### ISSUE THREAD

**Issue by outpaddling** [noyesno/awka#2] opened 2020-10-15 13:52 UTC
Just discovered awka - potentially very useful in bioinformatics where huge amounts of TSV data are processed.  It failed my first simple test, though, a small script I wrote to elucidate awk's logic in comparing numbers.

compare.awk:
```
BEGIN {
    x="10"
    y="9"
    printf("%s\n", x < y);  # Always 1
    
    x=10
    y=9
    printf("%s\n", x < y);  # Always 0

    getline x < "xy.txt"
    getline y < "xy.txt"
    printf("%s %s\n", x, y);
    printf("%s\n", x < y);  # awk 1, mawk and gawk 0
}

```
```
#!/bin/sh -e

for awk in awk gawk mawk 'awka -x'; do
    echo $awk
    $awk -f compare.awk
done

```
Output:
```
sh -c  ./awk-test 
awk
1
0
10 9
0
gawk
1
0
10 9
1
mawk
1
0
10 9
1
awka -x
1
0
 
1

```
xy.txt:
```
9
10

```

**Comment by jannick0** [comment] 2020-10-15 19:37
I cannot reproduce this behaviour for `awka -x`.  Does `getline` work as expected?   Are there any failing tests when running the package testsuite?

**Comment by jannick0** [comment] 2020-10-15 19:40
... and: would it be possible that awka is confused because of some EOL issue it it not prepared to cope with?

**Comment by outpaddling** [comment] 2020-10-16 00:19
Ugh, my bad.  I was not using the latest commit.  Rough day... Sorry for the noise.

**Comment by jannick0** [comment] 2020-10-16 09:33
No problem - glad that the issue resolved by itself.

**Comment by outpaddling** [comment] 2020-10-17 18:42
Actually there are some failures in make test.  This is FreeBSD 12.1, clang 8.0.1.

Do you by chance test on OS X?  I think it uses the same awk implementation as FreeBSD.

**Comment by jannick0** [comment] 2020-10-18 16:15
No - I am on a unix-like sytem.  With current master:
* the build of a shared library fails (so build switched off)
* the following tests fail: back89, fw, inftest, nfset, posix.

It appears that `getline x < "xy.txt"` does not work, since `x` might be the empty string. Did you do some research why this does not work?

**Comment by outpaddling** [comment] 2020-10-19 13:13
OS X is Unix-like.  Crude description: Mach kernel, mostly FreeBSD userland, a few GNU tools, Apple's GUI and extensions.

The getline works fine for me with your latest commit.  The original report was from an older version.

The exact same 4 tests fail for me, so at least it's consistent.  Do you know what's causing the failures?

Shared library build works fine on FreeBSD.

**Comment by noyesno** [comment] 2020-12-20 12:15
Exciting to know still having people showing interest to this project.

`make test` is now 100% PASS.  Together with some other code enhancement.
And add a continuous integration status badge to the page.

Mark this issue as "Closed".

**Closed as completed by noyesno** 2020-12-20 12:15 UTC
Labels: bug, Fixed

**Comment by outpaddling** [comment] 2020-12-20 13:58
Thanks!  I'll test the latest ASAP.

**Comment by outpaddling** [comment] 2020-12-20 22:11
make test is running clean on FreeBSD now, except for one warning in generated code:
```
cmp ./backgsub.ok _backgsub && rm -f _backgsub
x.c:269:5: warning: expression result unused [-Wunused-value]
    !strcmp(awka_gets(awka_doln(nf_tight_awk->dval, 0)), "N/A");
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
cmp ./tweakfld.ok _tweakfld && rm -f _tweakfld

```

**Comment by noyesno** [comment] 2020-12-21 00:00
> 
> 
> make test is running clean on FreeBSD now, except for one warning in generated code:
> 
> ```
> cmp ./backgsub.ok _backgsub && rm -f _backgsub
> x.c:269:5: warning: expression result unused [-Wunused-value]
>     !strcmp(awka_gets(awka_doln(nf_tight_awk->dval, 0)), "N/A");
>     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 warning generated.
> cmp ./tweakfld.ok _tweakfld && rm -f _tweakfld
> ```

It's due to testcase "tweakfld.awk" has below code. Should consider update the testcase.

The `-Wunused-value` compiler option is useful. Will consider added as default in **awka**.

```awk
# set TIGHT/LOOSE to N/A if it is not one of the two allowed values
function tight_na() {
    if( $nf_tight !~ /TIGHT|LOOSE/ ) {
        $nf_tight == "N/A"  ;# -- Result NOT Used Here
    }
}
```

**Comment by outpaddling** [comment] 2020-12-22 01:41
Yeah, from the comment it looks like that was meant to be an assignment, not a comparison.
